[package]
name = "jian-cha"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "jian-cha"
path = "jian-cha.rs"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
toml = "0.8"
comfy-table = "7.1"
indexmap = { version = "2.0", features = ["serde"] }
