# Personal notes repositories
[notes]
sw = "/Users/zvalenta/Documents/sw"
domains = "/Users/zvalenta/Documents/domains"

# Test sites
[test-sites]
test-zola-site = "/Users/zvalenta/Documents/test-zola-site"

# Development environment repositories
[denv]
bin = "/Users/zvalenta/Documents/denv/bin"
logs = "/Users/zvalenta/Documents/denv/logs"
dotfiles = "/Users/zvalenta/Documents/denv/dotfiles"

# Capp work logs
[capp-worklogs]
worklogs = "/Users/zvalenta/Documents/capp/worklogs"

# Capp RN projects
[capp-rn]
datalab = "/Users/zvalenta/Documents/capp/src/rn/datalab"
kern = "/Users/zvalenta/Documents/capp/src/rn/kern"
rfq-notebook = "/Users/zvalenta/Documents/capp/src/rn/rfq-notebook"
customer-quote-history = "/Users/zvalenta/Documents/capp/src/rn/customer-quote-history"

# Capp price updates by brand
[capp-price-updates]
baso = "/Users/zvalenta/Documents/capp/src/rn/price-updates/brands/baso"
aaon = "/Users/zvalenta/Documents/capp/src/rn/price-updates/brands/aaon"
copeland = "/Users/zvalenta/Documents/capp/src/rn/price-updates/brands/copeland"
reznor = "/Users/zvalenta/Documents/capp/src/rn/price-updates/brands/reznor"
bradford = "/Users/zvalenta/Documents/capp/src/rn/price-updates/brands/bradford"
mitsubishi-electric = "/Users/zvalenta/Documents/capp/src/rn/price-updates/brands/mitsubishi-electric"
baldor-motors = "/Users/zvalenta/Documents/capp/src/rn/price-updates/brands/baldor-motors"
uei = "/Users/zvalenta/Documents/capp/src/rn/price-updates/brands/uei"

# Capp backlog projects
[capp-backlog]
fuzzy-match = "/Users/zvalenta/Documents/capp/src/backlog/fuzzy-match"
pfp = "/Users/zvalenta/Documents/capp/src/backlog/pfp"
