[kero]
agentic = "/Users/zach/Documents/zv/work/kero/docs/agentic"
eng = "/Users/zach/Documents/zv/work/kero/docs/eng"
tickets = "/Users/zach/Documents/zv/work/kero/docs/tickets"
worklogs = "/Users/zach/Documents/zv/work/kero/docs/worklogs"
rush = "/Users/zach/Documents/zv/work/kero/src/automation/rush"

[denv]
# bin = "/Users/zach/Documents/denv/bin"
# logs = "/Users/zach/Documents/denv/logs"
# dotfiles = "/Users/zach/Documents/denv/dotfiles"

[notes]
sw = "/Users/zach/Documents/zv/notes/sw"
domains = "/Users/zach/Documents/zv/notes/domains"

[projects]
# myblog = "/Users/zach/Documents/zv/projects/active/sites/myblog"
# baby-track = "/Users/zach/Documents/zv/projects/active/personal/baby-track"
# jmore = "/Users/zach/Documents/zv/projects/active/data/mongo/jmore"
# wt-nosql = "/Users/zach/Documents/zv/projects/active/mongo/wt-nosql"
